; PlatformIO Project Configuration File
; M5Stack Cardputer MIDI Router/Hub

[env:m5stack-cardputer]
platform = espressif32
board = m5stack-stamps3
framework = espidf

build_flags =
    -DBOARD_HAS_PSRAM
    -I include

lib_deps =
    m5stack/M5GFX@^0.2.0

monitor_speed = 115200
upload_speed = 1500000
upload_port = /dev/cu.usbmodem*

board_build.partitions = default_8MB.csv
board_build.flash_size = 8MB
board_build.filesystem = littlefs
